apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
spec:
  version: 8.16.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
      cluster.routing.allocation.disk.threshold_enabled: false
